[build]
command = "npm run build"  # Adjust this to your build command for the frontend

[dev]
command = "npm run start"  # Adjust this to your start command for the backend
publish = "public"  # Adjust this to the directory where your frontend files are generated

[functions]
directory = "netlify/functions"  # Create this directory for your serverless functions

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api"  # Map API requests to serverless functions
status = 200