[build]
command = "npm run build"  # Adjust this to your build command for the frontend

[dev]
command = "npm run start"  # Adjust this to your start command for the backend
publish = "public"  # Adjust this to the directory where your frontend files are generated

[functions]
directory = "netlify/functions"  # Create this directory for your serverless functions

[[redirects]]
from = "/search/*"
to = "/.netlify/functions/search"  # Map API requests to serverless functions
status = 200

[[redirects]]
from = "/infinite/*"
to = "/.netlify/functions/infinite"  # Map API requests to serverless functions
status = 200

[[redirects]]
from = "/latest/*"
to = "/.netlify/functions/latest"  # Map API requests to serverless functions
status = 200